server {
    listen 8080;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    # --- Optimisation GZIP (Performance) ---
    gzip on;
    gzip_vary on;
    gzip_proxied any;
    gzip_comp_level 6;
    gzip_types text/plain text/css text/xml application/json application/javascript application/rss+xml application/atom+xml image/svg+xml;

    # --- Headers de Sécurité de base ---
    add_header X-Frame-Options "SAMEORIGIN"; # Protège contre le Clickjacking
    add_header X-Content-Type-Options "nosniff"; # Empêche le navigateur de deviner le type MIME
    add_header X-XSS-Protection "1; mode=block";

    # --- Routing Angular ---
    location / {
        try_files $uri $uri/ /index.html;

        # Pas de cache pour index.html (pour avoir les mises à jour immédiatement)
        add_header Cache-Control "no-store, no-cache, must-revalidate";
    }

    # --- Gestion du Cache pour les assets statiques ---
    # Angular génère des fichiers avec hash (ex: main.63647.js), on peut les cacher "à l'infini"
    location ~* \.(?:css|js|jpg|jpeg|gif|png|ico|svg|woff|woff2|ttf|eot)$ {
        expires 1y;
        add_header Cache-Control "public, immutable";
        access_log off; # Réduit le bruit dans les logs
    }

    # Endpoint pour le Healthcheck OpenShift (Liveness Probe)
    location /health {
        access_log off;
        return 200 'healthy';
    }
}
